version: '2'
services:
  db:
    image: "mrlesmithjr/mysql:latest"
    volumes:
      - "db:/var/lib/mysql"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "phpipam"
      MYSQL_DATABASE: "phpipam"
      MYSQL_USER: "phpipam"
      MYSQL_PASSWORD: "phpipam"

  web:
    depends_on:
      - db
    image: "mrlesmithjr/phpipam:latest"
    links:
      - "db"
    ports:
      - "8000:80"
    restart: "always"
    environment:
      APACHE2_ENABLE_PHP: "true"
      PHPIPAM_DB_HOST: "db"
      PHPIPAM_DB_NAME: "phpipam"
      PHPIPAM_DB_PASS: "phpipam"
      PHPIPAM_DB_USER: "phpipam"
volumes:
  db:
